INSERT INTO `Responsibility_Center_tbl` (`rc_code`, `rc_name`)
VALUES
('1','LEGASPI TOWERS CENTER'),
('2','A. MABINI BRANCH'),
('3','BINONDO BRANCH'),
('4','CALOOCAN BRANCH'),
('6','SAN JUAN BRANCH'),
('7','CUBAO BRANCH'),
('9','DEL MONTE BRANCH'),
('10','MALABON BRANCH'),
('11','BLUMENTRITT BRANCH'),
('13','SUCAT-PARANAQUE BRANCH'),
('14','CLARK BRANCH'),
('16','SAN FERNANDO BRANCH'),
('17','VIGAN BRANCH'),
('18','DAGUPAN BRANCH'),
('21','BINAN BRANCH'),
('22','HAGONOY BRANCH'),
('23','LIPA BRANCH'),
('24','EDSA TAFT BRANCH'),
('25','VILLAMOR BRANCH'),
('26','STA. ROSA BRANCH'),
('27','MEYCAUAYAN BRANCH'),
('29','GUAGUA BRANCH'),
('30','ALAMINOS BRANCH'),
('31','URDANETA BRANCH'),
('32','HERBOSA BRANCH'),
('33','NEWPORT CITY BRANCH'),
('34','ORTIGAS BRANCH'),
('35','OLONGAPO BRANCH'),
('36','LAOAG BRANCH'),
('37','RUFINO BRANCH'),
('38','MAKATI AVENUE BRANCH'),
('39','TOMAS MORATO BRANCH'),
('41','LUCENA  BRANCH'),
('43','BACOLOD BRANCH'),
('44','ILOILO BRANCH'),
('45','CEBU BRANCH'),
('46','ROXAS BRANCH'),
('48','DAVAO BRANCH'),
('51','CAGAYAN DE ORO BRANCH'),
('53','BAGO BRANCH'),
('57','GLOBAL CITY BRANCH'),
('59','BEL-AIR BRANCH'),
('61','ZAMBOANGA BRANCH'),
('62','AYALA ALABANG BRANCH'),
('63','GREENHILLS BRANCH'),
('64','BAGUIO BRANCH'),
('65','CEBU MANDAUE BRANCH'),
('67','VALENZUELA BRANCH'),
('68','LAS PINAS BRANCH'),
('69','MARIKINA BRANCH'),
('70','GLOBAL CITY-SOUTH MARKET BR.'),
('71','MCKINLEY HILL BRANCH'),
('72','GLOBAL CITY - 32nd STREET'),
('73','TARLAC BRANCH'),
('75','DAVAO BUSINESS CENTER'),
('88','MAIN OFFICE BRANCH'),
('949','Office of the President'),
('913','Human Resources'),
('942','Corporate Planning'),
('945','Compliance '),
('914','Legal'),
('943','Office of the Corporate Secretary'),
('947','Corporate Affairs'),
('948','Security'),
('976','Risk Management Group Head'),
('971','Group Credit Management - Wholesale'),
('972','Group Credit Management - Retail'),
('973','Credit Risk Management'),
('974','Non Traded Market Risk '),
('975','Operational Risk Management'),
('937','Retail Business Group Head'),
('918','Consumer Finance Head'),
('961','Auto Finance - Head Office'),
('956','Auto Finance - Clark'),
('957','Auto Finance - Global City'),
('996','Floor Stock Finance'),
('958','Auto Finance - Laoag'),
('960','Auto Finance - Dagupan'),
('962','Auto Finance - Baguio'),
('963','Auto Finance - Cebu'),
('964','Auto Finance - Cagayan de Oro'),
('965','Auto Finance - Davao'),
('966','Auto Finance - Iloilo'),
('967','AFG - San Fernando'),
('968','Auto Finance - Urdaneta'),
('969','Auto Finance - Caloocan '),
('970','Auto Finance - Zamboanga'),
('919','Mortgage'),
('920','Personal & Salary Loan Head'),
('954','Regular Salary Loan'),
('997','Wholesale Salary Loan'),
('998','Motorcycle Channeling Loan'),
('953','Personal Loan'),
('889','Community Distribution Head'),
('926','Region Head - 1'),
('927','Region Head - 2'),
('928','Region Head - 3'),
('929','Region Head - 4'),
('934','Business Enablement'),
('890','Quality Assurance'),
('891','Resource Management'),
('940','Virtual Banking'),
('922','Business Development Head'),
('932','Brand Management & Marketing'),
('892','Customer Relationship Management'),
('887','Central Insurance Unit'),
('894','Cards Head'),
('955','Cards Acquiring'),
('895','Cards Issuing'),
('952','Internal Audit Head'),
('951','Internal Audit'),
('917','Services Group Head'),
('911','Accounting'),
('912','Information Systems'),
('915','Property Administration & Purchasing'),
('906','Reconciliation'),
('911','Phimay Property Inc'),
('896','Investment & Asset Management-Head'),
('946','Global Markets'),
('944','Trust'),
('899','Central Operations Group Head'),
('897','Binan Cash Center'),
('898','San Fernando Cash Center'),
('916','Global Market Support'),
('907','Loan Administration Department'),
('903','Remittance & Cable'),
('904','Central Cash & Clearing'),
('905','Business Process Management'),
('921','Trade Finance Operations'),
('936','Cash Management Services - Operations'),
('931','ATM Operations'),
('892','Credit & Remedial Management'),
('981','Centralized Collection'),
('982','Loan Management Center'),
('983','Litigation & ROPA Management'),
('885','CI & Appraisal Unit'),
('923','Global Banking Group Head '),
('985','Corporate Banking Head'),
('980','Corporate Banking'),
('950','Commercial Banking Head'),
('987','Commercial Banking 1'),
('988','Commercial Banking 2'),
('977','Regional Business Center - Iloilo'),
('938','Regional Business Center - Cebu'),
('939','Regional Business Center - Davao'),
('886','Transaction Banking'),
('883','Cash Management Services - GWB'),
('979','Trade Finance Marketing'),
('989','Real Estate Finance Head'),
('991','Real Estate Finance Team 1'),
('992','Real Estate Finance Team 2'),
('993','Credit Support Team'),
('994','Marketing Support Team'),
('978','SME Lending');
